const axios = require("axios");
const properties = [
    {
        id: 1,
        title: "Cozy Apartment in Downtown",
        price: 120000,
        address: "123 Main St, City",
        bedrooms: 2,
        bathrooms: 1,
        hospitalsNearby: "City Hospital",
        schoolsNearby: "Downtown Elementary School",
    },
    {
        id: 2,
        title: "Spacious Villa in Suburbs",
        price: 450000,
        address: "456 Elm St, City",
        bedrooms: 4,
        bathrooms: 3,
        hospitalsNearby: "Suburban Medical Center",
        schoolsNearby: "Suburb High School",
    },
    {
        id: 3,
        title: "Modern Loft in City Center",
        price: 350000,
        address: "789 Oak St, City",
        bedrooms: 1,
        bathrooms: 1,
        hospitalsNearby: "Central Health Clinic",
        schoolsNearby: "City Center Middle School",
    },
    {
        id: 4,
        title: "Luxury Condo with Sea View",
        price: 600000,
        address: "101 Pine St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Sea View Hospital",
        schoolsNearby: "Ocean View School",
    },
    {
        id: 5,
        title: "Charming Cottage",
        price: 250000,
        address: "202 Maple St, City",
        bedrooms: 2,
        bathrooms: 2,
        hospitalsNearby: "Maple Health Center",
        schoolsNearby: "Maple Elementary School",
    },
    {
        id: 6,
        title: "Family House with Garden",
        price: 300000,
        address: "303 Birch St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Birchwood Hospital",
        schoolsNearby: "Birchwood High School",
    },
    {
        id: 7,
        title: "Modern Apartment with Balcony",
        price: 280000,
        address: "404 Cedar St, City",
        bedrooms: 2,
        bathrooms: 1,
        hospitalsNearby: "Cedar Health Clinic",
        schoolsNearby: "Cedar Primary School",
    },
    {
        id: 8,
        title: "Rustic Cabin in the Woods",
        price: 150000,
        address: "505 Spruce St, City",
        bedrooms: 2,
        bathrooms: 1,
        hospitalsNearby: "Woodland Medical Center",
        schoolsNearby: "Spruce Elementary School",
    },
    {
        id: 9,
        title: "Beachfront Villa",
        price: 750000,
        address: "606 Palm St, City",
        bedrooms: 4,
        bathrooms: 3,
        hospitalsNearby: "Beachside Hospital",
        schoolsNearby: "Palm High School",
    },
    {
        id: 10,
        title: "Downtown Studio Apartment",
        price: 200000,
        address: "707 Ash St, City",
        bedrooms: 1,
        bathrooms: 1,
        hospitalsNearby: "City General Hospital",
        schoolsNearby: "Downtown Junior High",
    },
    {
        id: 11,
        title: "Suburban Family Home",
        price: 320000,
        address: "808 Willow St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Willow Health Clinic",
        schoolsNearby: "Willow High School",
    },
    {
        id: 12,
        title: "Contemporary Townhouse",
        price: 400000,
        address: "909 Fir St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Fir Medical Center",
        schoolsNearby: "Fir Elementary School",
    },
    {
        id: 13,
        title: "Historic Home in Old Town",
        price: 350000,
        address: "1010 Chestnut St, City",
        bedrooms: 4,
        bathrooms: 3,
        hospitalsNearby: "Old Town Hospital",
        schoolsNearby: "Chestnut High School",
    },
    {
        id: 14,
        title: "Luxury Penthouse",
        price: 950000,
        address: "1111 Walnut St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Walnut Health Clinic",
        schoolsNearby: "Walnut Primary School",
    },
    {
        id: 15,
        title: "Country Home with Land",
        price: 500000,
        address: "1212 Oakwood St, City",
        bedrooms: 4,
        bathrooms: 3,
        hospitalsNearby: "Oakwood Medical Center",
        schoolsNearby: "Oakwood High School",
    },
    {
        id: 16,
        title: "City Center Apartment",
        price: 280000,
        address: "1313 Pineview St, City",
        bedrooms: 2,
        bathrooms: 2,
        hospitalsNearby: "Pineview Hospital",
        schoolsNearby: "City Center Elementary",
    },
    {
        id: 17,
        title: "Lakefront Cabin",
        price: 270000,
        address: "1414 Lake St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Lake Health Clinic",
        schoolsNearby: "Lakeview School",
    },
    {
        id: 18,
        title: "Modern Studio Apartment",
        price: 220000,
        address: "1515 Riverside St, City",
        bedrooms: 1,
        bathrooms: 1,
        hospitalsNearby: "Riverside Hospital",
        schoolsNearby: "Riverside Junior High",
    },
    {
        id: 19,
        title: "Mountain Chalet",
        price: 450000,
        address: "1616 Hilltop St, City",
        bedrooms: 4,
        bathrooms: 3,
        hospitalsNearby: "Hilltop Medical Center",
        schoolsNearby: "Hilltop High School",
    },
    {
        id: 20,
        title: "Penthouse with City View",
        price: 800000,
        address: "1717 Skyline St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Skyline Health Clinic",
        schoolsNearby: "Skyline Primary School",
    },
    {
        id: 21,
        title: "Countryside Farmhouse",
        price: 600000,
        address: "1818 Country Ln, City",
        bedrooms: 4,
        bathrooms: 3,
        hospitalsNearby: "Country Medical Center",
        schoolsNearby: "Countryside School",
    },
    {
        id: 22,
        title: "Urban Loft",
        price: 400000,
        address: "1919 Uptown St, City",
        bedrooms: 2,
        bathrooms: 2,
        hospitalsNearby: "Uptown Health Clinic",
        schoolsNearby: "Uptown Junior High",
    },
    {
        id: 23,
        title: "Chic Downtown Condo",
        price: 350000,
        address: "2020 Center St, City",
        bedrooms: 1,
        bathrooms: 1,
        hospitalsNearby: "Central Hospital",
        schoolsNearby: "Downtown High School",
    },
    {
        id: 24,
        title: "Secluded Cabin",
        price: 180000,
        address: "2121 Forest St, City",
        bedrooms: 2,
        bathrooms: 1,
        hospitalsNearby: "Forest Health Center",
        schoolsNearby: "Forest Elementary School",
    },
    {
        id: 25,
        title: "Contemporary Apartment",
        price: 300000,
        address: "2222 River St, City",
        bedrooms: 2,
        bathrooms: 2,
        hospitalsNearby: "River Hospital",
        schoolsNearby: "River Primary School",
    },
    {
        id: 26,
        title: "Modern Family Home",
        price: 420000,
        address: "2323 Elmwood St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Elmwood Medical Center",
        schoolsNearby: "Elmwood High School",
    },
    {
        id: 27,
        title: "Urban Penthouse",
        price: 780000,
        address: "2424 Skyline St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Skyline Medical Center",
        schoolsNearby: "Skyline School",
    },
    {
        id: 28,
        title: "Suburban Ranch",
        price: 320000,
        address: "2525 Suburb St, City",
        bedrooms: 3,
        bathrooms: 2,
        hospitalsNearby: "Suburb Health Clinic",
        schoolsNearby: "Suburb High School",
    },
    {
        id: 29,
        title: "Historic Townhouse",
        price: 400000,
        address: "2626 Old Town St, City",
        bedrooms: 4,
        bathrooms: 3,
        hospitalsNearby: "Old Town Health Center",
        schoolsNearby: "Old Town Junior High",
    },
];

async function createBulk() {
    try {
        for (let property of properties) {
            delete property.id;
            let res = await axios.post(
                "http://localhost:8000/api/v1/properties/create",
                property,
                {
                    withCredentials: true,
                }
            );

            console.log(res);
        }
    } catch (err) {
        console.log(err);
    }
}

createBulk();
